variables:
  service_connection: 'dssandbox-spn'
  resource_group: 'PTAZSG-DEV-DSP-RG'
  app_name: 'ptsg-5dspwb04'
  slot_name: 'dstats'

pool:
  vmImage: ubuntu-latest

## No code trigger (events )
trigger: 
  branches:
    include:
    - deploy_v1

## Pipeline steps
steps:
  - task: UsePythonVersion@0
    displayName: "Setting Python version"
    inputs:
      versionSpec: '3.9'
      # architecture: 'x64'
      addToPath: true

  # Step 1, Make a venv, activate, install requirements, run collectstatic
  - script: |
      python -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "Dependencies installation completed"
      cd recruitment
      python manage.py collectstatic
      echo "Collectstatic completed"
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    displayName: "Install requirements"


   # Step 2, create zip file be deployed
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/recruitment"
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: 'drop'
    displayName: 'Publish build artifacts'

  
  # Step 3, deploy zip package to azure app service
  - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App : $(app_name)'
      inputs:
        azureSubscription: $(service_connection)
        appName: $(app_name)
        package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        deployToSlotOrASE: true # boolean. Optional. Use when appType != "". Deploy to Slot or App Service Environment. Default: false.
        resourceGroupName: $(resource_group) # string. Required when deployToSlotOrASE = true. Resource group. 
        slotName: $(slot_name) # string. Required when deployToSlotOrASE = true. Slot. Default: production.
