variables:
  service_connection: 'dssandbox-spn'
  resource_group: 'PTAZSG-DEV-DSP-RG'
  app_name: 'ptsg-5dspwb04'
  slot_name: 'dstats'

pool:
  vmImage: ubuntu-latest

## No code trigger (events )
trigger: 
  branches:
    include:
    - deploy_v1

## Pipeline steps
steps:
  - task: UsePythonVersion@0
    displayName: "Setting Python version"
    inputs:
      versionSpec: '3.9'
      # architecture: 'x64'
      addToPath: true

  - task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

  - script: |
      python -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "Dependencies installation completed"
      cd recruitment
      python manage.py collectstatic
      echo "Collectstatic completed"
    displayName: "Install requirements"
  
  # Step 3, deploy zip package to azure app service
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: $(service_connection)
      appType: 'webAppLinux'
      WebAppName: $(app_name)
      deployToSlotOrASE: true
      ResourceGroupName: $(resource_group)
      SlotName: $(slot_name)
      packageForLinux:  '$(System.DefaultWorkingDirectory)/'
      appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT true'
