# Generated by Django 4.2 on 2023-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_prescreening_initial_screening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescreening',
            name='user',
        ),
    ]
