# Generated by Django 4.2 on 2023-05-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_candidateresume_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='referral',
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='referral_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
