# Generated by Django 4.2 on 2023-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_candidate_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='submission',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='cbisubmission',
            name='submission',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='prescreeningsubmission',
            name='submission',
            field=models.BinaryField(editable=True),
        ),
    ]
