# Generated by Django 3.2.9 on 2023-06-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_merge_20230523_1757'),
        ('main', '0055_alter_candidate_date_alter_candidate_email_and_more'),
    ]

    operations = [
    ]
