# Generated by Django 4.2 on 2023-04-12 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('referral_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('highest_education', models.CharField(max_length=100)),
                ('years_exp', models.IntegerField()),
                ('CGPA', models.FloatField()),
                ('recent_role', models.CharField(max_length=100)),
                ('recent_emp', models.CharField(max_length=100)),
                ('main_skills', models.CharField(max_length=100)),
                ('ds_skills', models.CharField(max_length=100)),
                ('ds_background', models.CharField(max_length=100)),
                ('hr_remarks', models.TextField()),
                ('cv_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('selection_date', models.DateField(null=True)),
                ('referred_hr_date', models.DateField(null=True)),
                ('rereferred_hr_date', models.DateField(null=True)),
                ('availability', models.BooleanField(null=True)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screeningId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.screening')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='screening',
            name='selectionStatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_proposal', models.DateField(null=True)),
                ('offer_letter_rollout', models.DateField(null=True)),
                ('offer_letter_accept', models.DateField(null=True)),
                ('remark', models.TextField(null=True)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidates')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
        migrations.CreateModel(
            name='CBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('assessor1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_CBI', to=settings.AUTH_USER_MODEL)),
                ('assessor2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_CBI', to=settings.AUTH_USER_MODEL)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidates')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empcategory'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='last_modified_byId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidates',
            name='sourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source'),
        ),
        migrations.CreateModel(
            name='AssessorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='userCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercategory'),
        ),
        migrations.AddField(
            model_name='users',
            name='userPrivilegeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprivilege'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
