# Generated by Django 4.2 on 2023-04-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_userid_assessoravailability_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usercategory'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_privilege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userprivilege'),
        ),
    ]
