# Generated by Django 4.2 on 2023-04-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_users_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='selectionStatus',
            new_name='selection_status',
        ),
    ]
