# Generated by Django 4.2 on 2023-04-14 08:05

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_selectionstatus_screening_selection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(upload_to=main.models.PrescreeningSubmission.upload_directory)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.screening')),
            ],
        ),
    ]
