# Generated by Django 4.2 on 2023-04-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_screeningfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScreeningFiles',
            new_name='ScreeningSubmission',
        ),
    ]
