# Generated by Django 4.2 on 2023-04-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='hr_remarks',
            field=models.TextField(null=True),
        ),
    ]
