# Generated by Django 4.2 on 2023-04-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cbischedule_cbisubmission_initialscreening_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescreeningsubmission',
            old_name='initial_screening',
            new_name='prescreening',
        ),
    ]
