# Generated by Django 4.2 on 2023-04-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_initial_screening_prescreeningsubmission_prescreening'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='codename',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
