# Generated by Django 4.2 on 2023-04-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbi',
            name='is_proceed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbischedule',
            name='is_proceed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initialscreening',
            name='is_proceed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='is_proceed',
            field=models.BooleanField(default=False),
        ),
    ]
