# Generated by Django 4.2 on 2023-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cbi_is_proceed_cbischedule_is_proceed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbi',
            name='is_proceed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cbischedule',
            name='is_proceed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='initialscreening',
            name='is_proceed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='prescreening',
            name='is_proceed',
            field=models.BooleanField(null=True),
        ),
    ]
