# Generated by Django 4.2 on 2023-04-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_cbi_is_proceed_alter_cbischedule_is_proceed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialscreeningevaluation',
            name='is_proceed',
            field=models.BooleanField(null=True),
        ),
    ]
