# Generated by Django 4.2 on 2023-04-27 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_initialscreeningevaluation_is_proceed'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialscreeningevaluation',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='initialscreeningevaluation',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initscreening_user_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
