# Generated by Django 4.2 on 2023-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_initialscreeningevaluation_is_proceed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreening',
            name='is_sent_instruction',
            field=models.BooleanField(default=False),
        ),
    ]
