# Generated by Django 4.2 on 2023-04-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_prescreening_is_sent_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbi',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='initialscreening',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.candidate'),
        ),
        migrations.AlterField(
            model_name='prescreening',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.candidate'),
        ),
    ]
