# Generated by Django 4.2 on 2023-04-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_prescreeningsubmission_prescreening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescreening',
            name='initial_screening',
        ),
        migrations.AddField(
            model_name='prescreening',
            name='instruction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
