# Generated by Django 4.2 on 2023-04-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_modified_at_candidate_last_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbi',
            name='date',
        ),
        migrations.AlterField(
            model_name='cbischedule',
            name='assessor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2_CBISchedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cbischedule',
            name='assessor2_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2_status', to='main.status'),
        ),
        migrations.AlterField(
            model_name='cbischedule',
            name='assessor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user3_CBISchedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cbischedule',
            name='assessor3_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user3_status', to='main.status'),
        ),
        migrations.AlterField(
            model_name='cbischedule',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
