# Generated by Django 4.2 on 2023-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_cbi_date_alter_cbischedule_assessor2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbischedule',
            name='is_RSVP',
            field=models.BooleanField(default=False),
        ),
    ]
