# Generated by Django 4.2 on 2023-05-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_candidate_status_alter_candidate_gpt_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='status',
            new_name='overall_status',
        ),
    ]
