# Generated by Django 4.2 on 2023-05-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_status_candidate_overall_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialscreening',
            old_name='selection_date',
            new_name='date_selected',
        ),
        migrations.RenameField(
            model_name='initialscreening',
            old_name='selection_status',
            new_name='status',
        ),
    ]
