# Generated by Django 4.2 on 2023-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_selection_date_initialscreening_date_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='alias',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
