# Generated by Django 4.2 on 2023-05-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_initialscreening_hm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialscreening',
            name='hm_date_selected',
            field=models.DateField(null=True),
        ),
    ]
