# Generated by Django 4.2 on 2023-05-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_initialscreening_hm_date_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
