# Generated by Django 4.2 on 2023-05-22 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_candidateresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='candidate_name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.source'),
        ),
    ]
