# Generated by Django 3.2.9 on 2023-05-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20230518_1609'),
        ('main', '0046_alter_candidateresume_candidate_name'),
    ]

    operations = [
    ]
