# Generated by Django 4.2 on 2023-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_candidateresume_is_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ds_background',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ds_skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='main_skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recent_emp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recent_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_exp',
            field=models.IntegerField(null=True),
        ),
    ]
