# Generated by Django 4.2 on 2023-06-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_candidateresume_is_parsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.candidateresume'),
        ),
    ]
