# Generated by Django 4.2.1 on 2023-07-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_candidate_gpt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='overall_remarks',
            field=models.TextField(null=True),
        ),
    ]
