# Generated by Django 3.2.9 on 2023-06-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_nationality_candidate_nationality'),
        ('main', '0058_alter_candidate_name'),
    ]

    operations = [
    ]
