# Generated by Django 3.2.9 on 2023-06-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_parserconfiguration'),
        ('main', '0059_merge_20230615_1539'),
    ]

    operations = [
    ]
