# Generated by Django 3.2.9 on 2023-07-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_candidate_gpt_score'),
        ('main', '0060_merge_20230621_1047'),
    ]

    operations = [
    ]
