# Generated by Django 3.2.9 on 2023-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_merge_20230621_1047'),
        ('main', '0061_alter_candidate_years_exp'),
    ]

    operations = [
    ]
