# Generated by Django 3.2.9 on 2023-07-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_candidate_ds_background_and_more'),
        ('main', '0062_merge_20230718_1733'),
    ]

    operations = [
    ]
