# Generated by Django 3.2.9 on 2023-07-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_merge_20230709_1613'),
        ('main', '0063_alter_candidate_cgpa_alter_candidate_email_and_more'),
    ]

    operations = [
    ]
