# Generated by Django 4.2.1 on 2023-07-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_candidate_cgpa_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='test_column',
            field=models.TextField(null=True),
        ),
    ]
