# Generated by Django 3.2.9 on 2023-07-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_candidate_cgpa_alter_candidate_email_and_more'),
        ('main', '0064_auto_20230719_0555'),
    ]

    operations = [
    ]
